Removes unsupported links. Fixes formatting.
ipfs/ipfs-docs pull request #1003
Opened 2022-01-24 18:11 UTC by johnnymatthews

Closes #988.

Removes unsupported example from a `:::tip` section. Also cleans up some funky formatting and hard-coded HTML links (booo).

2022-01-24 18:14 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/glossary.md`:
- The following link returned HTTP status code 302 (Found):
  https://docs.libp2p.io/concepts/circuit-relay
- The following link returned HTTP status code 301 (Moved Permanently):
  https://github.com/ipfs/research-CRDT
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a peer can tell othe...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other peers on the network. More about Bootstrapping # C # CBOR The Concise...
                                             ^^^^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.<!--CategoryID:STYLE, RuleID: EN_WEAK_ADJECTIVE-->
  ```
  ..."Qm". Uses a base 58-encoded multihash, very simple but much less flexible t...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Circuit relay” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...re versions of CID. More about CID v1 # Circuit relay Circuit relay is a tra...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...out Circuit Relay  (opens new window) # Codec A function that encodes or dec...
                                             ^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...mented as part of Multicodec. # Content addressing A way to store informatio...
                                             ^^^^^^^^^^
  ```
- Use a comma before ‘so’ if it connects two independent clauses (unless they are closely connected and short).<!--CategoryID:PUNCTUATION, RuleID: COMMA_COMPOUND_SENTENCE_2-->
  ```
  ...nt addressing A way to store information so a device can retrieve the data b...
                                             ^^^
  ```
- Although a hyphen is possible, it is not necessary in a compound modifier in which the first word is an adverb that ends in ‘ly’.<!--CategoryID:STYLE, RuleID: HYPHENATED_LY_ADVERB_ADJECTIVE-->
  ```
  ...eplicated Data Type (CRDT) is a type of specially-designed data structure us...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- Consider using “many”.<!--CategoryID:REDUNDANCY, RuleID: NUMEROUS_DIFFERENT-->
  ```
  ... systems, blockchains, and for modeling many different kinds of information....
                                             ^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...n Wikipedia  (opens new window). # Data model Did you mean IPLD Data Model  ...
                                             ^^^^^
  ```
- It appears that a comma is missing.<!--CategoryID:PUNCTUATION, RuleID: COMMA_BEFORE_QUESTION_WITH_MD-->
  ```
  ...ipedia  (opens new window). # Data model Did you mean IPLD Data Model  (open...
                                             ^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ubset of the IPFS DHT. More about DHT # DMT Short for Data Model Tree, a ter...
                                             ^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a connection is open...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # DNSLink DNSLink is a ...
                                             ^^^^^^^^^^^
  ```
- ‘by accident’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...le webpage, website, or service, either by accident or on purpose. # E # F #...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Garbage Collection” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...ore about Gateway  (opens new window) # Garbage Collection Garbage Collectio...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘under discussion’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...lternative content replication protocol under discussion, similar to Bitswap...
                                             ^^^^^^^^^^^^^^^^
  ```
- ‘exact same’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...) and returns a fixed-length value. The exact same input data will always ge...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...re numerous hash algorithms. More about Hash # I # Information Space Informa...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably use “Information Space” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ... hash algorithms. More about Hash # I # Information Space Information Space ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘in support of’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...(IPLD) model is a set of specifications in support of decentralized data str...
                                             ^^^^^^^^^^^^^
  ```
- This expression is ususally spelled with a hyphen<!--CategoryID:COMPOUNDING, RuleID: SPECIFIC_HYPHEN-->
  ```
  ...SON is a text format that is completely language independent, human-readable...
                                             ^^^^^^^^^^^^^^^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...ther node. This is opposed to a root. # libp2p The libp2p project is a modul...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...This is opposed to a root. # libp2p The libp2p project is a modular system o...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...essential component of IPFS. More about libp2p  (opens new window) # Listeni...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein an incoming connecti...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # Link In IPFS and IPLD...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘as’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_AT_AS-->
  ```
  ... a computer science data structure used at the core of IPFS files/block stor...
                                             ^^
  ```
- The preposition ‘of’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_TO_OF-->
  ```
  ...lock storage. Merkle-DAGs create a hash to t [...]

2022-01-24 21:02 UTC, lidel requested changes
Tweaks lgtm, but the example about content-addressed paths should stay :)

2022-01-31 21:13 UTC, johnnymatthews commented on docs/how-to/address-ipfs-on-web.md
> -User agents without IPFS support still get the correct data from the original HTTP server.
Resolved in https://github.com/ipfs/ipfs-docs/pull/1003/commits/f164befe857a12d84d999c08161ef0616132b0f2

2022-01-31 21:15 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/glossary.md`:
- The following link returned HTTP status code 302 (Found):
  https://docs.libp2p.io/concepts/circuit-relay
- The following link returned HTTP status code 301 (Moved Permanently):
  https://github.com/ipfs/research-CRDT
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a peer can tell othe...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other peers on the network. More about Bootstrapping # C # CBOR The Concise...
                                             ^^^^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.<!--CategoryID:STYLE, RuleID: EN_WEAK_ADJECTIVE-->
  ```
  ..."Qm". Uses a base 58-encoded multihash, very simple but much less flexible t...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Circuit relay” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...re versions of CID. More about CID v1 # Circuit relay Circuit relay is a tra...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...out Circuit Relay  (opens new window) # Codec A function that encodes or dec...
                                             ^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...mented as part of Multicodec. # Content addressing A way to store informatio...
                                             ^^^^^^^^^^
  ```
- Use a comma before ‘so’ if it connects two independent clauses (unless they are closely connected and short).<!--CategoryID:PUNCTUATION, RuleID: COMMA_COMPOUND_SENTENCE_2-->
  ```
  ...nt addressing A way to store information so a device can retrieve the data b...
                                             ^^^
  ```
- Although a hyphen is possible, it is not necessary in a compound modifier in which the first word is an adverb that ends in ‘ly’.<!--CategoryID:STYLE, RuleID: HYPHENATED_LY_ADVERB_ADJECTIVE-->
  ```
  ...eplicated Data Type (CRDT) is a type of specially-designed data structure us...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- Consider using “many”.<!--CategoryID:REDUNDANCY, RuleID: NUMEROUS_DIFFERENT-->
  ```
  ... systems, blockchains, and for modeling many different kinds of information....
                                             ^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...n Wikipedia  (opens new window). # Data model Did you mean IPLD Data Model  ...
                                             ^^^^^
  ```
- It appears that a comma is missing.<!--CategoryID:PUNCTUATION, RuleID: COMMA_BEFORE_QUESTION_WITH_MD-->
  ```
  ...ipedia  (opens new window). # Data model Did you mean IPLD Data Model  (open...
                                             ^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ubset of the IPFS DHT. More about DHT # DMT Short for Data Model Tree, a ter...
                                             ^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a connection is open...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # DNSLink DNSLink is a ...
                                             ^^^^^^^^^^^
  ```
- ‘by accident’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...le webpage, website, or service, either by accident or on purpose. # E # F #...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Garbage Collection” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...ore about Gateway  (opens new window) # Garbage Collection Garbage Collectio...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘under discussion’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...lternative content replication protocol under discussion, similar to Bitswap...
                                             ^^^^^^^^^^^^^^^^
  ```
- ‘exact same’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...) and returns a fixed-length value. The exact same input data will always ge...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...re numerous hash algorithms. More about Hash # I # Information Space Informa...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably use “Information Space” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ... hash algorithms. More about Hash # I # Information Space Information Space ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘in support of’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...(IPLD) model is a set of specifications in support of decentralized data str...
                                             ^^^^^^^^^^^^^
  ```
- This expression is ususally spelled with a hyphen<!--CategoryID:COMPOUNDING, RuleID: SPECIFIC_HYPHEN-->
  ```
  ...SON is a text format that is completely language independent, human-readable...
                                             ^^^^^^^^^^^^^^^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...ther node. This is opposed to a root. # libp2p The libp2p project is a modul...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...This is opposed to a root. # libp2p The libp2p project is a modular system o...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...essential component of IPFS. More about libp2p  (opens new window) # Listeni...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein an incoming connecti...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # Link In IPFS and IPLD...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘as’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_AT_AS-->
  ```
  ... a computer science data structure used at the core of IPFS files/block stor...
                                             ^^
  ```
- The preposition ‘of’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_TO_OF-->
  ```
  ...lock storage. Merkle-DAGs create a hash to t [...]

2022-01-31 21:15 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/glossary.md`:
- The following link returned HTTP status code 302 (Found):
  https://docs.libp2p.io/concepts/circuit-relay
- The following link returned HTTP status code 301 (Moved Permanently):
  https://github.com/ipfs/research-CRDT
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a peer can tell othe...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other peers on the network. More about Bootstrapping # C # CBOR The Concise...
                                             ^^^^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.<!--CategoryID:STYLE, RuleID: EN_WEAK_ADJECTIVE-->
  ```
  ..."Qm". Uses a base 58-encoded multihash, very simple but much less flexible t...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Circuit relay” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...re versions of CID. More about CID v1 # Circuit relay Circuit relay is a tra...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...out Circuit Relay  (opens new window) # Codec A function that encodes or dec...
                                             ^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...mented as part of Multicodec. # Content addressing A way to store informatio...
                                             ^^^^^^^^^^
  ```
- Use a comma before ‘so’ if it connects two independent clauses (unless they are closely connected and short).<!--CategoryID:PUNCTUATION, RuleID: COMMA_COMPOUND_SENTENCE_2-->
  ```
  ...nt addressing A way to store information so a device can retrieve the data b...
                                             ^^^
  ```
- Although a hyphen is possible, it is not necessary in a compound modifier in which the first word is an adverb that ends in ‘ly’.<!--CategoryID:STYLE, RuleID: HYPHENATED_LY_ADVERB_ADJECTIVE-->
  ```
  ...eplicated Data Type (CRDT) is a type of specially-designed data structure us...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- Consider using “many”.<!--CategoryID:REDUNDANCY, RuleID: NUMEROUS_DIFFERENT-->
  ```
  ... systems, blockchains, and for modeling many different kinds of information....
                                             ^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...n Wikipedia  (opens new window). # Data model Did you mean IPLD Data Model  ...
                                             ^^^^^
  ```
- It appears that a comma is missing.<!--CategoryID:PUNCTUATION, RuleID: COMMA_BEFORE_QUESTION_WITH_MD-->
  ```
  ...ipedia  (opens new window). # Data model Did you mean IPLD Data Model  (open...
                                             ^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ubset of the IPFS DHT. More about DHT # DMT Short for Data Model Tree, a ter...
                                             ^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a connection is open...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # DNSLink DNSLink is a ...
                                             ^^^^^^^^^^^
  ```
- ‘by accident’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...le webpage, website, or service, either by accident or on purpose. # E # F #...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Garbage Collection” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...ore about Gateway  (opens new window) # Garbage Collection Garbage Collectio...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘under discussion’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...lternative content replication protocol under discussion, similar to Bitswap...
                                             ^^^^^^^^^^^^^^^^
  ```
- ‘exact same’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...) and returns a fixed-length value. The exact same input data will always ge...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...re numerous hash algorithms. More about Hash # I # Information Space Informa...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably use “Information Space” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ... hash algorithms. More about Hash # I # Information Space Information Space ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘in support of’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...(IPLD) model is a set of specifications in support of decentralized data str...
                                             ^^^^^^^^^^^^^
  ```
- This expression is ususally spelled with a hyphen<!--CategoryID:COMPOUNDING, RuleID: SPECIFIC_HYPHEN-->
  ```
  ...SON is a text format that is completely language independent, human-readable...
                                             ^^^^^^^^^^^^^^^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...ther node. This is opposed to a root. # libp2p The libp2p project is a modul...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...This is opposed to a root. # libp2p The libp2p project is a modular system o...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...essential component of IPFS. More about libp2p  (opens new window) # Listeni...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein an incoming connecti...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # Link In IPFS and IPLD...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘as’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_AT_AS-->
  ```
  ... a computer science data structure used at the core of IPFS files/block stor...
                                             ^^
  ```
- The preposition ‘of’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_TO_OF-->
  ```
  ...lock storage. Merkle-DAGs create a hash to t [...]

2022-01-31 21:17 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/glossary.md`:
- The following link returned HTTP status code 302 (Found):
  https://docs.libp2p.io/concepts/circuit-relay
- The following link returned HTTP status code 301 (Moved Permanently):
  https://github.com/ipfs/research-CRDT
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a peer can tell othe...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other peers on the network. More about Bootstrapping # C # CBOR The Concise...
                                             ^^^^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.<!--CategoryID:STYLE, RuleID: EN_WEAK_ADJECTIVE-->
  ```
  ..."Qm". Uses a base 58-encoded multihash, very simple but much less flexible t...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Circuit relay” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...re versions of CID. More about CID v1 # Circuit relay Circuit relay is a tra...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...out Circuit Relay  (opens new window) # Codec A function that encodes or dec...
                                             ^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...mented as part of Multicodec. # Content addressing A way to store informatio...
                                             ^^^^^^^^^^
  ```
- Use a comma before ‘so’ if it connects two independent clauses (unless they are closely connected and short).<!--CategoryID:PUNCTUATION, RuleID: COMMA_COMPOUND_SENTENCE_2-->
  ```
  ...nt addressing A way to store information so a device can retrieve the data b...
                                             ^^^
  ```
- Although a hyphen is possible, it is not necessary in a compound modifier in which the first word is an adverb that ends in ‘ly’.<!--CategoryID:STYLE, RuleID: HYPHENATED_LY_ADVERB_ADJECTIVE-->
  ```
  ...eplicated Data Type (CRDT) is a type of specially-designed data structure us...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- Consider using “many”.<!--CategoryID:REDUNDANCY, RuleID: NUMEROUS_DIFFERENT-->
  ```
  ... systems, blockchains, and for modeling many different kinds of information....
                                             ^^^^^^^^^^^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...n Wikipedia  (opens new window). # Data model Did you mean IPLD Data Model  ...
                                             ^^^^^
  ```
- It appears that a comma is missing.<!--CategoryID:PUNCTUATION, RuleID: COMMA_BEFORE_QUESTION_WITH_MD-->
  ```
  ...ipedia  (opens new window). # Data model Did you mean IPLD Data Model  (open...
                                             ^^^^
  ```
- Possible missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ubset of the IPFS DHT. More about DHT # DMT Short for Data Model Tree, a ter...
                                             ^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein a connection is open...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # DNSLink DNSLink is a ...
                                             ^^^^^^^^^^^
  ```
- ‘by accident’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...le webpage, website, or service, either by accident or on purpose. # E # F #...
                                             ^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably use “Garbage Collection” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...ore about Gateway  (opens new window) # Garbage Collection Garbage Collectio...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘under discussion’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...lternative content replication protocol under discussion, similar to Bitswap...
                                             ^^^^^^^^^^^^^^^^
  ```
- ‘exact same’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...) and returns a fixed-length value. The exact same input data will always ge...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...re numerous hash algorithms. More about Hash # I # Information Space Informa...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably use “Information Space” only once.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ... hash algorithms. More about Hash # I # Information Space Information Space ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘in support of’ might be wordy. Consider a shorter alternative.<!--CategoryID:STYLE, RuleID: EN_WORDINESS_PREMIUM-->
  ```
  ...(IPLD) model is a set of specifications in support of decentralized data str...
                                             ^^^^^^^^^^^^^
  ```
- This expression is ususally spelled with a hyphen<!--CategoryID:COMPOUNDING, RuleID: SPECIFIC_HYPHEN-->
  ```
  ...SON is a text format that is completely language independent, human-readable...
                                             ^^^^^^^^^^^^^^^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...ther node. This is opposed to a root. # libp2p The libp2p project is a modul...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...This is opposed to a root. # libp2p The libp2p project is a modular system o...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...essential component of IPFS. More about libp2p  (opens new window) # Listeni...
                                             ^^^^^^
  ```
- Possible typo detected.<!--CategoryID:TYPOS, RuleID: NUMBERS_IN_WORDS-->
  ```
  ...unction of the IPFS networking layer in libp2p, wherein an incoming connecti...
                                             ^^^^^^
  ```
- Uncountable nouns are usually not used with an indefinite article. Use simply “transport”.<!--CategoryID:GRAMMAR, RuleID: A_UNCOUNTABLE-->
  ```
  ...entation of dialing and listening forms a transport. # Link In IPFS and IPLD...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘as’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_AT_AS-->
  ```
  ... a computer science data structure used at the core of IPFS files/block stor...
                                             ^^
  ```
- The preposition ‘of’ seems more likely in this position.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_REPLACE_TO_OF-->
  ```
  ...lock storage. Merkle-DAGs create a hash to t [...]

2022-01-31 21:17 UTC, merged