Clarifies where the IPFS icon is on menubar
ipfs/ipfs-docs pull request #1015
Opened 2022-02-01 21:56 UTC by Annamarie2019

I'd like to add an image.

2022-02-01 21:58 UTC, bertrandfalguiere commented
Isn't that just valid for MacOS?

2022-02-08 15:57 UTC, johnnymatthews requested changes
I've requested some changes. Just go through these comments @Annamarie2019 and commit my suggestions, then we're good to go with merging this.

2022-02-08 15:57 UTC, johnnymatthews commented on docs/install/ipfs-desktop.md
> +| Files screen                                                               | Explore screen                                                                 | Peers screen
```suggestion
| Files screen                                                               | Explore screen                                                                 | Peers screen                                                               | Settings screen                                                                  | Menubar/taskbar                                                                      |
```

This is OS-specific. We don't want to do that.

2022-02-08 15:57 UTC, johnnymatthews commented on docs/install/ipfs-desktop.md
> +- **Start your node at system startup (Mac/Windows) and control it from your OS** by right-clicking the IPFS icon on the top right of your computer's menubar. <!-- ![IPFS Menubar Icon](.images/ipfs-m
```suggestion
- **Start your node at system startup (Mac/Windows) and control it from your OS** using the convenient menubar/system tray menu.
```

Again, the location of the IPFS icon is specific to each operating system. We can expect users to know where to look if we say _status bar icon_ or something like that. Revert this back to the original.

2022-02-08 15:57 UTC, johnnymatthews commented on docs/install/ipfs-desktop.md
> +- **Quick download for CIDs, IPFS paths, and IPNS paths** — choose `Download...` by right-clicking the IPFS icon on your computer's menubar, paste in a hash, and you're good to go.
This is good!

2022-02-10 21:51 UTC, Annamarie2019 commented
...so I've committed all changes, so I believe my work is done here, yes?

2022-02-15 21:08 UTC, johnnymatthews approved these changes

2022-02-15 21:08 UTC, merged