Adds an explanation for each profile
ipfs/ipfs-docs pull request #1018
Opened 2022-02-03 19:57 UTC by Annamarie2019

My apologies if this is a duplicate. (I had some confusion when I forked a previous version, but I don't see the PR anywhere and the article is not updated, so I'm thinking I need to resubmit correctly.) 
I think I get the process for subsequent forking and PRs, so they should go more smoothly from here on out.

2022-02-08 16:07 UTC, johnnymatthews requested changes
Suggested a couple of changes.

2022-02-08 16:07 UTC, johnnymatthews commented on docs/how-to/default-profile.md
> +### Available only when initializing the node:
```suggestion
### Available only when initializing the node

These profiles can only be used prior to running `ipfs init`.
```

Try not to add punctuation to titles. I can cause issues with markdown links.

2022-02-08 16:07 UTC, johnnymatthews commented on docs/how-to/default-profile.md
> +### Available at any time:
```suggestion
### Available at any time

These profiles can be used anytime after running `ipfs init`. You may have to restart your IPFS node for the profile changes to take effect.
```

2022-02-09 21:50 UTC, Annamarie2019 commented
Closing this PR:
- found better solution
- found better PR workflow
Issue #604 now resolved in  https://github.com/ipfs/ipfs-docs/pull/1024

2022-02-09 21:50 UTC, closed without merging