Create Simple Chat App Update
ipfs/ipfs-docs pull request #1161
Opened 2022-05-26 16:04 UTC by TheDiscordian

Updated diagram, changed links to be up-to-date, removed Docker section, added warning about circuit-relay v1 removal from go-ipfs & linked to a repo with most of the code needed to use the chat app /w a relay (but missing pubsub & the ability to list addrs, so no announcing) fixes #1146

This simply makes the guide correct again, however doesn't instruct the user on how to setup a circuit-relay anymore. The reason for this being is [go-libp2p-relay-daemon](https://github.com/libp2p/go-libp2p-relay-daemon) doesn't currently have any way to:

1. Announce over pubsub
2. List connected addresses

So unless I missed something, while it's awesome having most of the hard work needed done, it's still not enough to bring life to using circuit-relay in a browser right now, not that I can figure out anyways. In the future I or someone else can likely take the [Python script](https://gist.github.com/TheDiscordian/51962fea72f8d5a5c3bba79dd7009e1c) which is used for advertising currently, and build a custom libp2p node that bundles the pubsub announces right into it, which would completely solve the problem.

2022-05-26 17:14 UTC, johnnymatthews commented on docs/how-to/create-simple-chat-app.md
> +This section is currently only relevant for go-ipfs versions **before** v0.11.0 as it's about circuit relay v1. There is currently no solution available to directly replace it, though most of the wor
```suggestion
This section is currently only relevant for go-ipfs versions **before** v0.11.0 as it's about circuit relay v1. There is currently no solution available to directly replace it, though most of the work [has been completed](https://github.com/libp2p/go-libp2p-relay-daemon).
```

2022-05-26 17:14 UTC, johnnymatthews approved these changes
Looks good. Merge when ready.

2022-05-27 23:41 UTC, lidel requested changes

2022-05-27 23:41 UTC, lidel commented on docs/how-to/create-simple-chat-app.md
> +This section is currently only relevant for go-ipfs versions **before** v0.11.0 as it's about circuit relay v1. There is currently no solution available to directly replace it, though most of the wor
@TheDiscordian was there a hard blocker that made you write this? iiuc configuring it to be `RelayV1: true`  should be drop-in replacement, no?

```suggestion
This section is currently only relevant for go-ipfs versions **before** v0.11.0 as circuit relay v1 server is no longer provided with go-ipfs. There is currently a standalone solution available  [go-libp2p-relay-daemon](https://github.com/libp2p/go-libp2p-relay-daemon#readme) configured as `RelayV1: true`.
```

2022-05-27 23:47 UTC, lidel approved these changes
This is fine as band-aid (adds note that go-ipfs 0.11 needs to be used), but does not remove  references to deprecated `EnableRelayHop` from our docs.

We should keep  #1146 open until we remove all mentions.

2022-05-27 23:47 UTC, merged