Add cloudflare peer IDs
ipfs/ipfs-docs pull request #1171
Opened 2022-06-08 22:51 UTC by mathew-cf

2022-06-10 15:33 UTC, BigLep approved these changes

2022-06-10 16:12 UTC, mathew-cf commented on docs/how-to/peering-with-content-providers.md
> +|`QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE`|`/dnsaddr/bootstrap.cloudflare-ipfs.com/ipfs/QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE`|
I'm still working on opening up ingress to the IP. May have been a bit too early with this PR

2022-06-13 18:54 UTC, johnnymatthews commented
Looks like you're still working on this. I'm gonna convert it to a draft. Ping folks when you're ready for a review.

2022-07-27 23:18 UTC, mathew-cf commented
This is ready for review. Our peer count limit is fairly low as of right now but you should be able to ping our nodes without issue
```
$ ipfs ping /dnsaddr/node-12.ingress.cloudflare-ipfs.com/ipfs/QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev
PING QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev.
Pong received: time=70.94 ms
Pong received: time=94.22 ms
Pong received: time=83.20 ms
Pong received: time=74.81 ms
Pong received: time=74.89 ms
Pong received: time=79.82 ms
Pong received: time=75.27 ms
Pong received: time=71.42 ms
Pong received: time=70.23 ms
Pong received: time=80.62 ms
Average latency: 77.54ms
```

2022-07-29 21:59 UTC, johnnymatthews commented
Nice. I tried pinging (`ipfs ping ...`) each of them, and got a pong from most.

2022-07-29 22:14 UTC, johnnymatthews requested changes
I can't reach these three nodes:

```
QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z
QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
```

Are they actually up? I'm at an airport, so there's a chance that the WiFi here is bugging out.

2022-07-29 22:14 UTC, johnnymatthews commented on docs/how-to/peering-with-content-providers.md
> +| `QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z` | `/dnsaddr/node-2.ingress.cloudflare-ipfs.com`  |
Didn't get a response for this one.

2022-07-29 22:14 UTC, johnnymatthews commented on docs/how-to/peering-with-content-providers.md
> +| `QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx` | `/dnsaddr/node-4.ingress.cloudflare-ipfs.com`  |
Didn't get a response for this one.

2022-07-29 22:14 UTC, johnnymatthews commented on docs/how-to/peering-with-content-providers.md
> +| `QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G` | `/dnsaddr/node-6.ingress.cloudflare-ipfs.com`  |
Didn't get a response for this one.

2022-08-11 09:57 UTC, isaadabbasi commented
> I can't reach these three nodes:
> 
> ```
> QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z
> QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
> QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
> ```
> 

I verified and still these 3 nodes are unreachable. Any update on this?

2022-08-15 15:34 UTC, johnnymatthews commented
> > I can't reach these three nodes:
> > ```
> > QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z
> > QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
> > QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
> > ```
> 
> I verified and still these 3 nodes are unreachable. Any update on this?

I just tried this again. The first and last gave me a pong! But the middle (`QmcfJ...Uswx`) didnt:

```shell
$ › ipfs ping QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z
PING QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z.
Pong received: time=145.87 ms
$ › ipfs ping QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
Looking up peer QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
PING QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx.
Ping error: failed to dial QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx:
  * [/ip4/136.144.57.127/tcp/4002/ws/p2p/12D3KooWJbARcvvEEF4AAqvAEaVYRkEUNPC3Rv3joebqfPh4LaKq/p2p-circuit] dial backoff
  * [/ip6/2604:1380:45f1:4d00::3/tcp/4002/ws/p2p/12D3KooWJbARcvvEEF4AAqvAEaVYRkEUNPC3Rv3joebqfPh4LaKq/p2p-circuit] error opening hop stream to relay: context deadline exceeded
  * [/ip4/136.144.57.127/tcp/4001/p2p/12D3KooWJbARcvvEEF4AAqvAEaVYRkEUNPC3Rv3joebqfPh4LaKq/p2p-circuit] error opening relay circuit: NO_RESERVATION (204)
  * [/ip6/2604:1380:45f1:4d00::3/tcp/4001/p2p/12D3KooWJbARcvvEEF4AAqvAEaVYRkEUNPC3Rv3joebqfPh4LaKq/p2p-circuit] concurrent active dial through the same relay failed with a protocol error
Error: ping failed
$ › ipfs ping QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
Looking up peer QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
PING QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G.
Pong received: time=85.61 ms
```

2022-08-16 08:10 UTC, 2color commented
Just ran a test to ping all the nodes and they were all reachable 

I got a few `Error: peer lookup failed: routing: not found` but after trying a couple of times it worked and I got a `Pong received`.

| Peer ID                                          | ipfs ping peerId |
| ------------------------------------------------ | ---------------- |
| `QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE` | ✅               |
| `QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z` | ✅               |
| `QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa` | ✅               |
| `QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx` | ✅               |
| `QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ` | ✅               |
| `QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G` | ✅               |
| `QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3` | ✅               |
| `QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP` | ✅               |
| `Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi` | ✅               |
| `QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx` | ✅               |
| `Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5` | ✅               |
| `QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev` | ✅               |

2022-08-16 14:56 UTC, johnnymatthews approved these changes

2022-08-16 14:57 UTC, johnnymatthews commented
Tried all the peers again and got responses from everything! Merging!

2022-08-16 14:57 UTC, merged