add core members for the ipfs docs
ipfs/ipfs-docs pull request #1265
Opened 2022-08-30 15:53 UTC by jennijuju

2022-08-30 15:55 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-09-01 04:45 UTC, 2color approved these changes
LGTM

2022-09-02 16:52 UTC, DannyS03 requested changes

2022-09-02 16:52 UTC, DannyS03 commented on README.md
>  ## Core members
```suggestion
## Primary maintainers
```

2022-09-02 16:52 UTC, DannyS03 commented on README.md
> +- [@TMoMoreau](https://github.com/TMoMoreau): Primary contact, tech writer(engineering)
```suggestion
- [@TMoMoreau](https://github.com/TMoMoreau): Primary contact, technical writing(engineering)
```

2022-09-02 16:52 UTC, DannyS03 commented on README.md
> +- [@johnnymatthews](https://github.com/johnnymatthews): Project leadership, organization
```suggestion
- [@johnnymatthews](https://github.com/johnnymatthews): Project leadership & organization
```

2022-09-02 16:52 UTC, DannyS03 commented on README.md
> +- [@2color](https://github.com/2color): Dev Rel, tech writer(ecosystem)
```suggestion
- [@2color](https://github.com/2color): Developer relations & technical writing(ecosystem)
- [@dannyS03](https://github.com/DannyS03}: Technical writing(engineering) 
```

2022-09-02 16:52 UTC, DannyS03 commented on README.md
> +- [@jennijuju](https://github.com/jennijuju): TPM
```suggestion
- [@jennijuju](https://github.com/jennijuju): Management and supervision
```

2022-09-02 18:08 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-09-02 18:08 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-09-02 18:09 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-09-02 18:09 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-09-02 18:09 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-09-02 19:28 UTC, DannyS03 approved these changes

2022-09-02 19:29 UTC, merged