feat: ipfs comparisons
ipfs/ipfs-docs pull request #1363
Opened 2022-12-12 05:34 UTC by DannyS03

## Context
- Document on comparing IPFS to other [similar] storage solutions
- Incorporates some suggestions in the linked issue and utilizes a table to compare common parameters and features
- resolves #779

## Latest preview

Please view the latest Fleek preview [here]().

2022-12-12 05:37 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-12-12 23:52 UTC, ElPaisano requested changes
Hi @DannyS03 I like the idea of adding this info into the docs. 

Made a few review notes

RE location in the docs: I'm not sure how I feel about this page being in Case Studies. The way I understand a Case Studies section, it's a section of the docs where examples of applications / other things that use / integrate / build on the software (in this case, IPFS), so this page feels out of place in this section, since it's a comparison of IPFS to other technologies. I'd actually suggest adding it as a subsection on the /concepts/what-is-ipfs/ page instead or at least somewhere in the IPFS 101 subsection under Concepts. Open to thoughts here

2022-12-12 23:52 UTC, ElPaisano commented on docs/concepts/comparisons.md
> +IPFS is a general-purpose file system that uses a distributed hash table (DHT) to store and retrieve data. This sets it apart from other solutions with a more specific focus or using different data s
Suggestion: This sentence 
```
This sets it apart from other solutions with a more specific focus or using different data storage mechanisms. For example:
```
reads a little strange. I think rephrasing it to something like
```
This sets it apart from other storage solutions that use different data storage mechanisms or have a more specific focus .  Similar solutions include:
```
would read better.

2022-12-12 23:52 UTC, ElPaisano commented on docs/concepts/comparisons.md
> +> Note that all these solutions use content-based addressing.
Two comments:
- Phrasing suggestion "Note that all of these solutions use content-based addressing."
- Might be better to use a callout box here:
   ```
   :::callout
   Note that all of these solutions use content-based addressing. 
   ::::
   ```

2022-12-12 23:52 UTC, ElPaisano commented on docs/concepts/comparisons.md
> +  > Filecoin is built on IPFS and uses the IPFS network for data storage and retrieval. Filecoin and IPFS are complementary technologies providing decentralized and efficient storage solutions.
Would suggest a `:::callout` here

2022-12-13 11:36 UTC, 2color commented on docs/.vuepress/config.js
> +              ['/concepts/comparisons', 'Comparisons'],
This isn't a case study. I would consider putting this in the IPFS 101 category.

2022-12-13 12:03 UTC, 2color requested changes
I would recommend making a clear distinction between two main categories here:
- Crypto-economic networks like Filecoin and Arweave
- Protocols made for moving (routing & transferring) bytes around like BitTorrent, Hypercore, IPFS

I'd also split those into two different tables to avoid creating a misleading comparison between the two categories

Some illuminating resources: 
https://blog.mauve.moe/posts/protocol-comparisons
https://medium.com/decentralized-web/comparing-ipfs-and-dat-8f3891d3a603

2022-12-13 12:03 UTC, 2color commented on docs/concepts/comparisons.md
> +- [Dat](https://datproject.org/) is a decentralized data-sharing tool that uses a distributed hash table (DHT) for data storage. It focuses on enabling data sharing and collaboration.
It's more commonly referred to as the Hypercore protocol nowadays. https://hypercore-protocol.org/

2022-12-13 16:25 UTC, ElPaisano commented on docs/.vuepress/config.js
> +              ['/concepts/comparisons', 'Comparisons'],
> I'd actually suggest adding it as a subsection on the /concepts/what-is-ipfs/ page instead or at least somewhere in the IPFS 101 subsection under Concepts. 

Seems like there's a shared consensus here @DannyS03. Can you move this out to IPFS 101?

2022-12-13 16:29 UTC, ElPaisano commented on docs/concepts/comparisons.md
> +# Storage Solution Comparisons
@2color created this issue https://github.com/ipfs/ipfs-docs/issues/1368 based on your callout. I also added your notion to the docs reorg notion

2022-12-13 16:41 UTC, 2color commented on docs/concepts/comparisons.md
> +# Storage Solution Comparisons
Thanks, @ElPaisano. That's great

2022-12-13 16:44 UTC, 2color commented
Btw, I should add that this page is very valuable. Might be worth also adding Git, which is also a distributed content-addressed system that has many parallels to IPFS.

2022-12-13 16:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-12-13 16:51 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-12-13 16:55 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-12-14 03:23 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2022-12-16 17:03 UTC, ElPaisano approved these changes

2022-12-16 17:04 UTC, ElPaisano commented
@DannyS03 changes look good 👍 @2color looks like DannyS03 addressed your changes. Is this good to go from your end? If so, we can merge once you approve.

2022-12-17 08:19 UTC, 2color approved these changes

2022-12-17 08:23 UTC, DannyS03 commented
Thanks for the suggestions @ElPaisano @2color! To Daniel's point, let's continue keeping an eye out for this page and consider other solutions + comparisons.

2022-12-17 08:24 UTC, merged