Add warning about js-ipfs being discontinued in a few places
ipfs/ipfs-docs pull request #1466
Opened 2023-01-30 23:25 UTC by ElPaisano

# Describe your changes
Addresses https://github.com/ipfs/ipfs-docs/issues/1465 and [Part 1 of issue 1459](https://github.com/ipfs/ipfs-docs/issues/1459#issuecomment-1409131076)

## Checklist before requesting a review
- [ ] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [ ] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

2023-01-30 23:31 UTC, ElPaisano commented
@2color I added this callout in the following places:

Install IPFS for JavaScript (js-ipfs)
IPFS Implementations
Create a simple chat app
IPFS repository guide > Protocol implementations

Any other spots you think we ought to add this in?

2023-01-31 07:55 UTC, 2color commented on docs/concepts/ipfs-implementations.md
> +Development of the [js-ipfs project](https://github.com/ipfs/js-ipfs) is being discontinued to focus on [Helia](https://github.com/ipfs/helia), a leaner, more modular, modern implementation of IPFS i
I would move this either to below the table or into the js-ipfs row so it's not the first thing you read on the page.

Also, this is the first time I've seen `slated` used this way. Looking it up reveals that it's a north American word which probably explains why I haven't seen it. What do you think about a more neutral verb, e.g. scheduled or planned?

2023-01-31 12:55 UTC, 2color requested changes
The new warning element itself is great.

I would also add it to the following pages:
- https://docs.ipfs.tech/reference/js/api/
- https://docs.ipfs.tech/concepts/nodes/#js-ipfs

2023-02-01 09:41 UTC, 2color approved these changes

2023-02-01 09:42 UTC, 2color commented
Either here or in a separate PR, e.g. #1360, we should add Helia to the list of implementation

2023-02-01 17:56 UTC, ElPaisano commented
> Either here or in a separate PR, e.g. #1360, we should add Helia to the list of implementation



> Either here or in a separate PR, e.g. #1360, we should add Helia to the list of implementation

👍 made a note to address it as part of https://github.com/ipfs/ipfs-docs/issues/1465, will create a quick PR

2023-02-01 17:57 UTC, merged