Update JS examples to v1, add code sandbox
ipfs/ipfs-docs pull request #1476
Opened 2023-02-03 02:10 UTC by ElPaisano

2023-02-03 02:20 UTC, ElPaisano commented
@TMoMoreau can you review this for copy / writing things? Once we do that, I'll pass it to @2color to confirm the tech

2023-02-03 17:53 UTC, 2color commented on docs/concepts/content-addressing.md
> +const cidV1StringBase256 = cidV1.toString(base16);
I think it may make sense to show where `base16` comes from (the import) and maybe even the how cidV1 is instantiated?

2023-02-03 17:57 UTC, 2color requested changes
Have you had a chance to take a look at https://github.com/ipfs/ipfs-docs/pull/1467?

I am torn on whether we want to have the code examples on this concepts page or move it into a guide.

If we include it, I would consider including both a Go and JS example and use the tab functionality like in the https://docs.ipfs.tech/how-to/ipfs-updater/ page.

2023-02-23 13:54 UTC, 2color approved these changes
Since this corrects some old packages referenced in the docs, I'm inclined to approve this already and address any additional changes in a separate PR

2023-03-20 14:18 UTC, merged