CLI publishing guide for w3
ipfs/ipfs-docs pull request #1548
Opened 2023-04-04 15:31 UTC by TheDiscordian

# Describe your changes
`docs/quickstart/publish_cli.md`

# What issue(s) does this address?

Closes #1513 

## Checklist before requesting a review
- [ ] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [ ] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

2023-04-04 15:37 UTC, TheDiscordian commented
BTW "Check Markdown links for modified files / markdown-link-check" failed because it incorrectly received a 403, perhaps Filebase is blocking the probe.

2023-04-05 22:11 UTC, ElPaisano reviewed
Looks good overall, just some nitpicks with steps, and rephrasing some stuff to distinguish it from the copy its based off of

I need to manually add one change in cus the review tool wasn't behaving

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
Break apart steps for readbability, copyability

For some reason, the change suggester isn't formatting this properly. I'll add it manually

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
1. Create a space for your files.

   ```shell
    w3 space create Pictures
   ```
   
1. Register your files.
  
   ```shell
   w3 space register
   ```

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +Congratulations, you have successfully **pinned** a file to IPFS! 🎉
```suggestion
Congratulations, you have successfully **pinned** a file to IPFS using the w3 cli! 🎉
```

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +- The [following image](../quickstart/images/welcome-to-IPFS.jpg), downloaded and saved on your computer:
```suggestion
- A unix-like terminal.
- Node.js installed in the terminal environment.
- The [following image](../quickstart/images/welcome-to-IPFS.jpg), downloaded and saved on your computer:
```

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +1. Install the w3 cli tool.
```suggestion
1. Install the [w3 command line interface](https://github.com/web3-storage/w3cli).
```

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +1. Register to w3 using your email.
```suggestion
1. Authorize the w3 tool to act on behalf of the account associated with your email address `<your@email.com>`:
```

2023-04-05 22:11 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   w3 authorize your@email.com
```suggestion
   w3 authorize <your@email.com>
```

2023-04-05 22:23 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
```suggestion
1. Create a space for your files.

   ```shell
    w3 space create Pictures
   ```
   
1. Register your files.
  
   ```shell
   w3 space register
   ```
```

2023-04-05 22:37 UTC, ElPaisano reviewed
Titles, formatting, nits, fix a few issues my first edit introduced 🤭

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +title: 'Publish a file with IPFS using a pinning service in a CLI'
```suggestion
title: 'Publish using the command line'
```

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +description: 'Learn how to publish content with IPFS by pinning a file to a pinning service using a CLI.'
```suggestion
description: 'Learn how to publish content with IPFS by pinning a file to a pinning service using the command line.'
```

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +# Publish a file with IPFS
```suggestion
# Publish a file with IPFS using the command line
```

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +
```suggestion

   ```shell
    w3 space create Pictures
   ```
   
```

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
```suggestion

   ```shell
   npm install -g @web3-storage/w3cli
   ```
```

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
```suggestion
   ```shell
   w3 authorize <your@email.com>
   ```
```

2023-04-05 22:37 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
```suggestion
   ```shell
```

2023-04-05 22:39 UTC, ElPaisano commented on docs/quickstart/publish_cli.md
> +   ```
added in https://github.com/ipfs/ipfs-docs/pull/1548/commits/3c6a6fb5f71bfc5e41f7609bfd5cf73f1cc22367

2023-04-05 22:52 UTC, ElPaisano requested changes
In my initial passes, missed the fact that this is missing a menu entry in the config file. That needs to be added in or this won't be visible / accessible from the menu

2023-04-06 00:07 UTC, merged

2023-04-06 00:15 UTC, ElPaisano commented
@TheDiscordian I merged all of this into https://github.com/ipfs/ipfs-docs/pull/1551 to finish up the remaining edits. I'll tag you as reviewer on #1551 so that you can sanity check my updates.