Helia and js-ipfs stragglers
ipfs/ipfs-docs pull request #1639
Opened 2023-07-24 18:01 UTC by ElPaisano

Addresses @BigLep unaddressed comments on merged [PR 1620](https://github.com/ipfs/ipfs-docs/pull/1620). Comments are here https://github.com/ipfs/ipfs-docs/pull/1620#pullrequestreview-1530749239

2023-07-24 18:05 UTC, ElPaisano commented
@BigLep I think I've addressed everything in the comments except the issue that https://docs.ipfs.tech/install/js-ipfs/#install-js-ipfs is still documenting js-ipfs and not Helia. I can use the wiki to create a "quickstart" that more or less mirrors the existing flow i.e. install, spawn a node, add a file, etc., what do think? Will change the file name and add redirects.

2023-07-24 18:41 UTC, SgtPooki requested changes

2023-07-24 18:41 UTC, SgtPooki commented on docs/concepts/faq.md
> +You can learn more about IPFS design standards and architectural specifications at [specs.ipfs.tech](https://specs.ipfs.tech/). The IPFS Standards website documents these standards and specifcations
```suggestion
You can learn more about IPFS design standards and architectural specifications at [specs.ipfs.tech](https://specs.ipfs.tech/). The IPFS Standards website documents these standards and specifications with the goal of fostering interoperability between independent implementations of the IPFS stack through Internet-grade specifications and test suites. 
```

2023-07-24 18:41 UTC, SgtPooki commented on docs/concepts/faq.md
> +- [InterPlanetary Improvement Proposals (IPIPs)](https://specs.ipfs.tech/meta/ipip-process/) are a focused, transparent, communit-driven process for protocol design discussions. They are not changes
```suggestion
- [InterPlanetary Improvement Proposals (IPIPs)](https://specs.ipfs.tech/meta/ipip-process/) are a focused, transparent, community-driven process for protocol design discussions. They are not changes to the specification itself, but their approval leads to a change in the specification.
```

2023-07-24 18:41 UTC, SgtPooki commented on docs/concepts/faq.md
> +If you would like to develop an IPFS implementation or are already working on one, the IPFS design standards and architectural specifications at [specs.ipfs.tech](https://specs.ipfs.tech/) are a grea
```suggestion
If you want to develop an IPFS implementation or are already working on one, the IPFS design standards and architectural specifications at [specs.ipfs.tech](https://specs.ipfs.tech/) are a great resource. In particular, the following resources are great starting points:
```

2023-07-24 18:41 UTC, SgtPooki commented on docs/concepts/faq.md
> +- [IPFS Principles](https://specs.ipfs.tech/architecture/principles/), which provides context and details around the core IPFS principles of content-addressing and transport-agnosticity. The document
```suggestion
- [IPFS Principles](https://specs.ipfs.tech/architecture/principles/) provides context and details around the core IPFS principles of content-addressing and transport-agnosticism. The document defines what is or is not an IPFS implementation.
```

2023-07-24 18:41 UTC, SgtPooki commented on docs/concepts/faq.md
> +- The [Meta](https://specs.ipfs.tech/meta/) section, which describes important non-technical information for contributors like what core project values, the governance model, how to produce documents
```suggestion
- The [Meta](https://specs.ipfs.tech/meta/) section describes important non-technical information for contributors, like the core project values, the governance model, how to produce documents, and more. 
```

2023-07-24 18:41 UTC, SgtPooki commented on docs/concepts/faq.md
> +In addition to these core documentats, `specs.ipfs.tech` documents standards for IPFS subsystems such as [InterPlanetary Naming System](https://specs.ipfs.tech/http-gateways/) and [HTTP Gateways](htt
```suggestion
In addition to these core documents, `specs.ipfs.tech` documents standards for IPFS subsystems such as the [InterPlanetary Naming System](https://specs.ipfs.tech/http-gateways/) and [HTTP Gateways](https://specs.ipfs.tech/http-gateways/).
```

2023-07-24 18:41 UTC, SgtPooki commented on docs/how-to/publish-ipns.md
> +IPNS names can be published programmatically.
```suggestion
IPNS names can be published programmatically.
```

2023-07-24 18:42 UTC, SgtPooki commented
> https://docs.ipfs.tech/install/js-ipfs/#install-js-ipfs is still documenting js-ipfs and not Helia. I can use the wiki to create a "quickstart" that more or less mirrors the existing flow i.e. install, spawn a node, add a file, etc., what do think? Will change the file name and add redirects.

Can we point users to helia-examples which will essentially be a living document?

2023-07-24 22:45 UTC, ElPaisano commented
@SgtPooki thanks for getting to the GH action-flagged issues as well as the other issues you caught. The remaining GH action-flagged issues are one false positive for the link check and a vale flag for "IPIPs", so we can ignore. I also went through again and made some more changes. 

Can I have you pull this branch down and build the local preview? I'm trying to determine if there is a build error  that will cause issues in prod or if its just my local environment. Will explain more if you encounter any local build errors.

2023-07-24 23:32 UTC, SgtPooki approved these changes

2023-07-25 00:05 UTC, merged

2023-07-25 04:58 UTC, BigLep reviewed
Thanks for updating