feat: rework gateway page and add recursive gateway
ipfs/ipfs-docs pull request #1966
Opened 2024-12-06 15:46 UTC by 2color

# Describe your changes

- Clean up deprecated and unhelpful content
- Add recursive/non-recursive to gateway types
- Add trusted and trustless gateways to gateway types

## Checklist before merging
- [ ] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

2024-12-06 16:04 UTC, 2color commented on docs/concepts/ipfs-gateway.md
> +## Gateway types
I wonder if it makes sense to add a "Gateway providers" type for non-recursive gateways

2024-12-06 18:32 UTC, lidel requested changes
Thank you for cleaning this up @2color, I found some easy wins while reading, suggestions below.

Most important is DNSLink section cleanup. If suggestions look goot to you, feel free to merge.

2024-12-06 18:32 UTC, lidel commented on docs/concepts/ipfs-gateway.md
>  ![Auth with Reverse proxy](./images/ipfs-gateways/public-authed-gateway.png)
nit: this image is wrong and confusing (gateway has no `/api/v0`), just remove it.

```suggestion
```

2024-12-06 18:32 UTC, lidel commented on docs/concepts/ipfs-gateway.md
> +This section uses the _default_ recursive gateway request lifecycle of [IPFS Kubo](https://github.com/ipfs/kubo) to introduce the basic concepts in the lifecycle. However, non-recursive gateways only
```suggestion
This section uses the _default_ recursive gateway request lifecycle of [IPFS Kubo](https://github.com/ipfs/kubo) to introduce the basic concepts in the lifecycle. However, non-recursive gateways only serve content that they have and/or want to provide. For example, a Kubo gateway with [`Gateway.NoFetch=true`](https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewaynofetch) will **not** attempt to retrieve content from the network.
```

2024-12-06 18:32 UTC, lidel commented on docs/concepts/ipfs-gateway.md
> +- **If the CID is not in the local cache**, the gateway will attempt to retrieve it from the network.
Good opportunity to show difference between both gw types?

```suggestion
- **If the CID is not in the local cache**, a non-recursive gateway would error, however our gateway is recursive and will attempt to retrieve it from the network.
```

2024-12-06 18:32 UTC, lidel commented on docs/concepts/ipfs-gateway.md
>  5. The browser does not perceive the gateway as the origin of the content and therefore enforces the single-origin policy to protect `example.com`.
Wow.. there is a lot of.. lets say untrue, controversial or vague statements in the old text here:
- We describe DNSLink name support on path gateway mixing it with logic and advanced setup based on `ALIAS` DNS record, and we are not mentioning `Host` header  case which is literally the core of https://specs.ipfs.tech/http-gateways/dnslink-gateway/
- Using alias is a gigantic footgun if you dont own both domains. It delegates authority to somneone, they can pretend to own your domain now. This is why Fleek uses CNAME for `_dnslink` subdomain, and nothing more.
- comment about origin isolation is incorrect (there is no isolation on path gateway, we protect noone)


I suspect this was glue together from various notes that made sense on their own, but in this form it is plain wrong.

Let's clean this up:

````suggestion
2. The gateway searches the DNS TXT records  on `_dnslink.` subdomain (`_dnslink.example.com`) for a string of the form `dnslink=/ipfs/{CID}`. If found, the gateway uses the specified content identifier to find and serve up `ipfs://{CID}/{optional path}`. 

It is possible to use HTTP gateway for serving content on the DNSLink domain itself:

1. Point `example.com` at IP of your HTTP gateway, make sure `A`/`AAAA`/`HTTPS` records are set, and TLS termination is configured.
2. Client sends request to:

   ```bash
   https://{example.com}/{optional path}
   ```

3. Gateway detects HTTP header `Host: example.com` in the incoming request and searches DNSLink the same way as in previous example.
````

2024-12-10 02:50 UTC, lidel commented on docs/concepts/ipfs-gateway.md
> +See [Trusted vs. Trustless Gateways](../reference/http/gateway/#trusted-vs-trustless) for more information.
```suggestion
See [Trusted vs. Trustless Gateways](../reference/http/gateway.md#trusted-vs-trustless) for more information.
```

2024-12-10 02:57 UTC, lidel approved these changes
Thanks! 

I've adjusted required branch protections in this repo to require new fleek  CI, hopefullu unblocking others to merge PRs in this repo (lmk if you get blocked again).

2024-12-10 02:57 UTC, merged