docs: cid conversion
ipfs/ipfs-docs pull request #734
Opened 2021-04-05 23:14 UTC by lidel

This PR adds basic docs about CID conversion (v0→v1, and text→binary).

Inspired by questions like https://github.com/multiformats/js-cid/issues/142

2021-04-06 14:30 UTC, jessicaschilling requested changes
Minor grammar/style nits. Thank you!

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +If you can't decide between CIDv0 and CIDv1, consider choosing CIDv1 for your new project and opt-in by passing version flag (`ipfs add --cid-version 1`). It is more future-proof and [safe for use in
```suggestion
If you can't decide between CIDv0 and CIDv1, consider choosing CIDv1 for your new project and opt in by passing a version flag (`ipfs add --cid-version 1`). This is more future-proof and [safe for use in browser contexts](/how-to/address-ipfs-on-web/#subdomain-gateway).
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +IPFS project will switch to CIDv1 as the new default in the near future.
```suggestion
The IPFS project will switch to CIDv1 as the new default in the near future.
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +Converting from v0 to v1 enables CID to be represented in one of multibase encodings.
```suggestion
Converting a CID from v0 to v1 enables it to be represented in multibase encodings.
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +The default for CIDv1 is case-insensitive `base32`, but use of shorter `base36` is encouraged for IPNS names to ensure same text representation on [subdomains](/how-to/address-ipfs-on-web/#subdomain-
```suggestion
The default for CIDv1 is the case-insensitive `base32`, but use of the shorter `base36` is encouraged for IPNS names to ensure same text representation on [subdomains](/how-to/address-ipfs-on-web/#subdomain-gateway).
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +and then decode the remainder using encoding specified in the [multibase table](https://github.com/multiformats/multibase#multibase-table).
```suggestion
and then decode the remainder using the encoding specified in the [multibase table](https://github.com/multiformats/multibase#multibase-table).
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +JS users can leverage the [`cids`](https://www.npmjs.com/package/cids) library to get binary version as `Uint8Array`:
```suggestion
JS users can leverage the [`cids`](https://www.npmjs.com/package/cids) library to get a binary version as `Uint8Array`:
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +::: warning Be mindful about parsing CID correctly and avoid shortcuts.
```suggestion
::: warning Be mindful about parsing CIDs correctly. Avoid shortcuts.
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +To convert back to a CIDv1, prepend hex value with `f` ([multibase prefix](https://github.com/multiformats/multibase#multibase-table) for lowercase base16).
```suggestion
To convert back to a CIDv1, prepend the hex value with `f` ([multibase prefix](https://github.com/multiformats/multibase#multibase-table) for lowercase base16).
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/content-addressing.md
> +[Subdomain gateways](/how-to/address-ipfs-on-web/#subdomain-gateway) convert paths with custom bases like base16 to base32 or base36 in effort to fit a CID in DNS label:
```suggestion
[Subdomain gateways](/how-to/address-ipfs-on-web/#subdomain-gateway) convert paths with custom bases like base16 to base32 or base36, in an effort to fit a CID in a DNS label:
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/glossary.md
> +Multicodec is an identifier, indicating the format of the target content. It helps people and software to know how to interpret that content after the content is fetched. In IPFS it is backed by an a
```suggestion
Multicodec is an identifier indicating the format of the target content. It helps people and software know how to interpret that content after the content is fetched. In IPFS, it is backed by an agreed-upon codec table. It is designed for use in binary representations, such as keys or identifiers (i.e [CIDv1](#cid)). [More about Multicodec](https://github.com/multiformats/multicodec#readme)
```

2021-04-06 14:30 UTC, jessicaschilling commented on docs/concepts/glossary.md
> +Multihash is a protocol for differentiating outputs from various well-established hash functions, addressing size + encoding considerations. It is useful to write applications that future-proof their
```suggestion
Multihash is a protocol for differentiating outputs from various well-established hash functions, addressing size and encoding considerations. It is useful to write applications that future-proof their use of hashes, and it allows multiple hash functions to coexist. [More about Multihash](https://multiformats.io/multihash/).
```

2021-04-06 14:43 UTC, lidel commented
Applied style changes, thank you @jessicaschilling !

2021-04-06 18:20 UTC, jessicaschilling approved these changes

2021-04-19 22:20 UTC, johnnymatthews commented
Sorry for the delay on my end getting to this. Looks good! Merging in staging.

2021-04-19 22:20 UTC, johnnymatthews approved these changes

2021-04-19 22:20 UTC, merged