[Concept] Add public gateway type - authenticated gateway
ipfs/ipfs-docs pull request #870
Opened 2021-08-27 07:59 UTC by zikunfan

2021-08-30 12:05 UTC, zikunfan commented
@johnnymatthews Could you please take a look at this PR?

2021-09-15 13:46 UTC, johnnymatthews requested changes
Here's a couple of minor suggestions. This is good to merge when they've been added.

2021-09-15 13:46 UTC, johnnymatthews commented on docs/concepts/ipfs-gateway.md
> +If the gateway providers want to limit the access only to the requests with authentication, they may need to config a reverse proxy, develop a IPFS plugin or set a cache-layer above IPFS.
```suggestion
If a gateway provider wants to limit access to requests with authentication, they may need to configure a reverse proxy, develop an IPFS plugin, or set a cache-layer above IPFS.
```

2021-09-15 13:46 UTC, johnnymatthews commented on docs/concepts/ipfs-gateway.md
> +Reverse proxy is the most popular way for providers handling authentication. This tutorial configuring private gateway includes a description of controling access with Nginx. Reverse proxy can also k
```suggestion
Configuring a reverse proxy is the most popular way for providers handling authentication. Reverse proxy can also keep the original IPFS API calls which makes gateway adaptable to all IPFS SDK and toolkits.
```

2021-09-15 13:46 UTC, johnnymatthews commented on docs/concepts/ipfs-gateway.md
> +Providers can design their own centralized auth service(like [Infura IPFS Auth](https://infura.io/docs/ipfs#section/Authentication/Overview)), or a decentralized auth service(like [IPFS W3Auth](https
```suggestion
Providers can design their own centralized authentication service like [Infura IPFS Auth](https://infura.io/docs/ipfs#section/Authentication/Overview), or a decentralized authentication service like [IPFS W3Auth](https://wiki.crust.network/docs/en/buildIPFSWeb3AuthGW)).
```

2021-09-16 03:30 UTC, zikunfan commented
@johnnymatthews Comments already resolved

2021-09-23 14:04 UTC, johnnymatthews approved these changes

2021-09-23 14:04 UTC, johnnymatthews commented on docs/concepts/ipfs-gateway.md
> +Configuring a reverse proxy is the most popular way for providers handling authentication. Reverse proxy can also keep the original IPFS API calls which makes gateway adaptable to all IPFS SDK and to
```suggestion
Configuring a reverse proxy is the most popular way for providers handling authentication. A reverse proxy can also keep the original IPFS API calls which makes gateway adaptable to all IPFS SDK and toolkits.
```

2021-09-23 14:10 UTC, merged